<?php

return [
    'validation' => [
        'update' => [
            'messages' => [
                'id.exists' => 'معرف القانوني المحدد غير صالح.',
                'locales.array' => 'يجب أن تكون اللغات مصفوفة.',
                'locales.min' => 'يجب أن تكون لغة واحدة على الأقل مطلوبة.',
                'locales.*.locale.required' => 'حقل اللغة مطلوب.',
                'locales.*.locale.string' => 'يجب أن تكون اللغة سلسلة نصية.',
                'locales.*.slug.filled' => 'يجب ملء الرابط المختصر إذا كان موجودًا.',
                'locales.*.slug.string' => 'يجب أن يكون الرابط المختصر سلسلة نصية.',
                'locales.*.slug.max' => 'لا يجوز أن يزيد الرابط المختصر عن 255 حرفًا.',
                'locales.*.short_content.string' => 'يجب أن يكون المحتوى القصير سلسلة نصية.',
                'locales.*.content.string' => 'يجب أن يكون المحتوى سلسلة نصية.',
                'locales.*.meta_title.string' => 'يجب أن يكون عنوان الصفحة سلسلة نصية.',
                'locales.*.meta_title.max' => 'لا يجوز أن يزيد عنوان الصفحة عن 255 حرفًا.',
                'locales.*.meta_description.string' => 'يجب أن يكون وصف الصفحة سلسلة نصية.',
                'locales.*.meta_keywords.string' => 'يجب أن تكون كلمات مفتاحية الصفحة سلسلة نصية.',

                'features.array' => 'يجب أن تكون الميزات مصفوفة.',
                'features.*.id.integer' => 'يجب أن يكون معرف الميزة عددًا صحيحًا.',
                'features.*.id.exists' => 'معرف الميزة المحدد غير صالح.',
                'features.*.file.file' => 'يجب أن يكون ملف الميزة ملفًا.',
                'features.*.file.max' => 'لا يجوز أن يزيد ملف الميزة عن 2048 كيلوبايت.',
                'features.*.sort_number.required' => 'رقم الترتيب مطلوب.',
                'features.*.sort_number.integer' => 'يجب أن يكون رقم الترتيب عددًا صحيحًا.',
                'features.*.locales.required' => 'لغات الميزة مطلوبة.',
                'features.*.locales.array' => 'يجب أن تكون لغات الميزة مصفوفة.',
                'features.*.locales.min' => 'يجب أن تكون لغة ميزة واحدة على الأقل مطلوبة.',
                'features.*.locales.*.locale.required' => 'حقل لغة الميزة مطلوب.',
                'features.*.locales.*.locale.string' => 'يجب أن تكون لغة الميزة سلسلة نصية.',
                'features.*.locales.*.title.required' => 'عنوان الميزة مطلوب.',
                'features.*.locales.*.title.string' => 'يجب أن يكون عنوان الميزة سلسلة نصية.',
                'features.*.locales.*.title.max' => 'لا يجوز أن يزيد عنوان الميزة عن 255 حرفًا.',
                'features.*.locales.*.description.string' => 'يجب أن يكون وصف الميزة سلسلة نصية.',
            ],
            'attributes' => [
                'id' => 'معرف القانوني',
                'locales' => 'اللغات',
                'locales.*.locale' => 'اللغة',
                'locales.*.slug' => 'الرابط المختصر',
                'locales.*.short_content' => 'المحتوى القصير',
                'locales.*.content' => 'المحتوى',
                'locales.*.meta_title' => 'عنوان الصفحة',
                'locales.*.meta_description' => 'وصف الصفحة',
                'locales.*.meta_keywords' => 'كلمات مفتاحية الصفحة',

                'features' => 'الميزات',
                'features.*.id' => 'معرف الميزة',
                'features.*.file' => 'ملف الميزة',
                'features.*.sort_number' => 'رقم الترتيب',
                'features.*.locales' => 'لغات الميزة',
                'features.*.locales.*.locale' => 'لغة الميزة',
                'features.*.locales.*.title' => 'عنوان الميزة',
                'features.*.locales.*.description' => 'وصف الميزة',
            ],
        ],
    ],
];
