<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Core System Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for core system functionality
    | and are not related to specific resources or frontend content.
    |
    */

    // System Messages
    'system' => [
        'title' => 'Content Management System',
        'version' => 'Version',
        'maintenance_mode' => 'Maintenance Mode',
        'maintenance_mode_on' => 'System is in maintenance mode',
        'maintenance_mode_off' => 'System is available',
        'system_error' => 'System Error',
        'database_error' => 'Database Error',
        'cache_cleared' => 'Cache cleared',
        'config_updated' => 'Configuration updated',
    ],

    // Authentication
    'auth' => [
        'login' => 'Login',
        'logout' => 'Logout',
        'register' => 'Register',
        'forgot_password' => 'Forgot Password',
        'reset_password' => 'Reset Password',
        'change_password' => 'Change Password',
        'profile' => 'Profile',
        'settings' => 'Settings',
        'unauthorized' => 'Unauthorized Access',
        'forbidden' => 'Access Forbidden',
        'session_expired' => 'Session Expired',
        'invalid_credentials' => 'Invalid Credentials',
        'account_locked' => 'Account Locked',
        'account_suspended' => 'Account Suspended',
    ],

    // Common UI Elements
    'ui' => [
        'loading' => 'Loading...',
        'saving' => 'Saving...',
        'processing' => 'Processing...',
        'searching' => 'Searching...',
        'no_results' => 'No Results',
        'no_data' => 'No Data',
        'empty_state' => 'Empty State',
        'error_occurred' => 'An Error Occurred',
        'success' => 'Success',
        'failed' => 'Failed',
        'warning' => 'Warning',
        'info' => 'Info',
        'confirm' => 'Confirm',
        'cancel' => 'Cancel',
        'ok' => 'OK',
        'yes' => 'Yes',
        'no' => 'No',
        'close' => 'Close',
        'save' => 'Save',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'view' => 'View',
        'back' => 'Back',
        'next' => 'Next',
        'previous' => 'Previous',
        'finish' => 'Finish',
        'continue' => 'Continue',
    ],

    // Form Elements
    'forms' => [
        'required' => 'Required',
        'optional' => 'Optional',
        'invalid' => 'Invalid',
        'valid' => 'Valid',
        'submit' => 'Submit',
        'reset' => 'Reset',
        'clear' => 'Clear',
        'select' => 'Select',
        'select_all' => 'Select All',
        'deselect_all' => 'Deselect All',
        'upload' => 'Upload',
        'browse' => 'Browse',
        'choose_file' => 'Choose File',
        'no_file_selected' => 'No File Selected',
        'file_selected' => 'File Selected',
        'max_file_size' => 'Maximum File Size',
        'allowed_file_types' => 'Allowed File Types',
    ],

    // Table and List
    'table' => [
        'no_data' => 'No Data Available',
        'loading' => 'Loading Data...',
        'search' => 'Search',
        'filter' => 'Filter',
        'sort' => 'Sort',
        'export' => 'Export',
        'import' => 'Import',
        'refresh' => 'Refresh',
        'select_all' => 'Select All',
        'deselect_all' => 'Deselect All',
        'selected_items' => 'Selected Items',
        'bulk_actions' => 'Bulk Actions',
        'per_page' => 'Per Page',
        'showing' => 'Showing',
        'to' => 'to',
        'of' => 'of',
        'results' => 'results',
    ],

    // Pagination
    'pagination' => [
        'previous' => 'Previous',
        'next' => 'Next',
        'first' => 'First',
        'last' => 'Last',
        'page' => 'Page',
        'pages' => 'Pages',
        'go_to_page' => 'Go to Page',
        'showing' => 'Showing',
        'to' => 'to',
        'of' => 'of',
        'results' => 'results',
        'per_page' => 'per page',
    ],

    // Status and States
    'status' => [
        'active' => 'Active',
        'inactive' => 'Inactive',
        'enabled' => 'Enabled',
        'disabled' => 'Disabled',
        'published' => 'Published',
        'draft' => 'Draft',
        'archived' => 'Archived',
        'pending' => 'Pending',
        'approved' => 'Approved',
        'rejected' => 'Rejected',
        'completed' => 'Completed',
        'in_progress' => 'In Progress',
        'cancelled' => 'Cancelled',
        'expired' => 'Expired',
        'valid' => 'Valid',
        'invalid' => 'Invalid',
    ],

    // Time and Date
    'time' => [
        'now' => 'Now',
        'today' => 'Today',
        'yesterday' => 'Yesterday',
        'tomorrow' => 'Tomorrow',
        'this_week' => 'This Week',
        'last_week' => 'Last Week',
        'next_week' => 'Next Week',
        'this_month' => 'This Month',
        'last_month' => 'Last Month',
        'next_month' => 'Next Month',
        'this_year' => 'This Year',
        'last_year' => 'Last Year',
        'next_year' => 'Next Year',
        'created_at' => 'Created At',
        'updated_at' => 'Updated At',
        'deleted_at' => 'Deleted At',
        'expires_at' => 'Expires At',
        'starts_at' => 'Starts At',
        'ends_at' => 'Ends At',
    ],

    // File and Media
    'media' => [
        'file' => 'File',
        'files' => 'Files',
        'image' => 'Image',
        'images' => 'Images',
        'video' => 'Video',
        'videos' => 'Videos',
        'audio' => 'Audio',
        'audio_files' => 'Audio Files',
        'document' => 'Document',
        'documents' => 'Documents',
        'archive' => 'Archive',
        'archives' => 'Archives',
        'upload' => 'Upload',
        'download' => 'Download',
        'delete' => 'Delete',
        'rename' => 'Rename',
        'move' => 'Move',
        'copy' => 'Copy',
        'preview' => 'Preview',
        'full_size' => 'Full Size',
        'thumbnail' => 'Thumbnail',
        'set_as_default' => 'Set as Default',
        'remove_default' => 'Remove Default',
        'sort_order' => 'Sort Order',
        'file_size' => 'File Size',
        'file_type' => 'File Type',
        'upload_date' => 'Upload Date',
    ],

    // Validation Messages
    'validation' => [
        'required' => 'This field is required',
        'invalid' => 'Invalid value',
        'not_found' => 'Item not found',
        'already_exists' => 'This item already exists',
        'cannot_delete' => 'Cannot delete this item',
        'permission_denied' => 'You do not have permission to perform this action',
        'unauthorized' => 'Unauthorized access',
        'forbidden' => 'Access forbidden',
        'validation_failed' => 'Validation failed',
        'invalid_format' => 'Invalid format',
        'too_short' => 'Value is too short',
        'too_long' => 'Value is too long',
        'too_small' => 'Value is too small',
        'too_large' => 'Value is too large',
        'must_be_unique' => 'Value must be unique',
        'must_be_different' => 'Value must be different',
        'must_match' => 'Values must match',
        'must_be_after' => 'Date must be after',
        'must_be_before' => 'Date must be before',
        'must_be_between' => 'Value must be between',
        'must_be_one_of' => 'Value must be one of',
        'must_not_be_one_of' => 'Value must not be one of',
    ],
];
