<?php

return [
    'validation' => [
        'update' => [
            'messages' => [
                'id.exists' => 'The selected legal ID is invalid.',
                'locales.array' => 'The locales must be an array.',
                'locales.min' => 'At least one locale is required.',
                'locales.*.locale.required' => 'The locale field is required.',
                'locales.*.locale.string' => 'The locale must be a string.',
                'locales.*.slug.filled' => 'The slug must be filled if present.',
                'locales.*.slug.string' => 'The slug must be a string.',
                'locales.*.slug.max' => 'The slug may not be greater than 255 characters.',
                'locales.*.short_content.string' => 'The short content must be a string.',
                'locales.*.content.string' => 'The content must be a string.',
                'locales.*.meta_title.string' => 'The meta title must be a string.',
                'locales.*.meta_title.max' => 'The meta title may not be greater than 255 characters.',
                'locales.*.meta_description.string' => 'The meta description must be a string.',
                'locales.*.meta_keywords.string' => 'The meta keywords must be a string.',

                'features.array' => 'The features must be an array.',
                'features.*.id.integer' => 'The feature ID must be an integer.',
                'features.*.id.exists' => 'The selected feature ID is invalid.',
                'features.*.file.file' => 'The feature file must be a file.',
                'features.*.file.max' => 'The feature file may not be greater than 2048 kilobytes.',
                'features.*.sort_number.required' => 'The sort number is required.',
                'features.*.sort_number.integer' => 'The sort number must be an integer.',
                'features.*.locales.required' => 'The feature locales are required.',
                'features.*.locales.array' => 'The feature locales must be an array.',
                'features.*.locales.min' => 'At least one feature locale is required.',
                'features.*.locales.*.locale.required' => 'The feature locale field is required.',
                'features.*.locales.*.locale.string' => 'The feature locale must be a string.',
                'features.*.locales.*.title.required' => 'The feature title is required.',
                'features.*.locales.*.title.string' => 'The feature title must be a string.',
                'features.*.locales.*.title.max' => 'The feature title may not be greater than 255 characters.',
                'features.*.locales.*.description.string' => 'The feature description must be a string.',
            ],
            'attributes' => [
                'id' => 'Legal ID',
                'locales' => 'Locales',
                'locales.*.locale' => 'Locale',
                'locales.*.slug' => 'Slug',
                'locales.*.short_content' => 'Short Content',
                'locales.*.content' => 'Content',
                'locales.*.meta_title' => 'Meta Title',
                'locales.*.meta_description' => 'Meta Description',
                'locales.*.meta_keywords' => 'Meta Keywords',

                'features' => 'Features',
                'features.*.id' => 'Feature ID',
                'features.*.file' => 'Feature File',
                'features.*.sort_number' => 'Sort Number',
                'features.*.locales' => 'Feature Locales',
                'features.*.locales.*.locale' => 'Feature Locale',
                'features.*.locales.*.title' => 'Feature Title',
                'features.*.locales.*.description' => 'Feature Description',
            ],
        ],
    ],
];
